services:
  console_command.count_phone_numbers:
    class: Mannion007\LongRunningProcess\Application\CountPhoneNumbersCommand
    arguments:
      - "@phone_numbers_publisher"
    tags:
      -  { name: console.command }

  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher

  symfony_dispatcher_event_publisher:
    class: Mannion007\LongRunningProcess\Infrastructure\SymfonyDispatcherEventPublisher
    arguments:
      - '@event_dispatcher'

  phone_number_provider:
    class: Mannion007\LongRunningProcess\Infrastructure\InMemoryPhoneNumberProvider

  search_result_logger:
    class: Mannion007\LongRunningProcess\Infrastructure\InMemorySearchResultLogger

  phone_numbers_publisher:
    class: Mannion007\LongRunningProcess\Domain\PhoneNumbersPublisher
    arguments:
      - '@phone_number_provider'
      - '@symfony_dispatcher_event_publisher'

  phone_number_finder:
    class: Mannion007\LongRunningProcess\Domain\PhoneNumberFinder
    arguments:
      - '@symfony_dispatcher_event_publisher'

  matched_phone_number_counter:
    class: Mannion007\LongRunningProcess\Domain\MatchedPhoneNumberCounter
    arguments:
      - '@symfony_dispatcher_event_publisher'

  phone_number_executive:
    class: Mannion007\LongRunningProcess\Domain\PhoneNumberExecutive
    arguments:
      - '@search_result_logger'

  find_phone_numbers_listener:
    class: Mannion007\LongRunningProcess\EventListener\FindPhoneNumbersListener
    arguments:
      - '@phone_number_finder'

  count_matched_phone_numbers_listener:
    class: Mannion007\LongRunningProcess\EventListener\CountMatchedPhoneNumbersListener
    arguments:
      - '@matched_phone_number_counter'

  log_search_result_listener:
    class: Mannion007\LongRunningProcess\EventListener\LogSearchResultListener
    arguments:
      - '@phone_number_executive'