services:
  console_command.count_phone_numbers:
    class: Mannion007\LongRunningProcess\Command\CountPhoneNumbersCommand
    arguments:
      - "@phone_number_executive"
    tags:
      -  { name: console.command }

  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher

  symfony_dispatcher_event_publisher:
    class: Mannion007\LongRunningProcess\Infrastructure\SymfonyDispatcherEventPublisher
    arguments:
      - '@event_dispatcher'

  phone_number_provider:
    class: Mannion007\LongRunningProcess\Infrastructure\InMemoryPhoneNumberProvider

  search_result_logger:
    class: Mannion007\LongRunningProcess\Infrastructure\InMemorySearchResultLogger

  phone_number_finder:
    class: Mannion007\LongRunningProcess\Domain\PhoneNumberFinder

  all_phone_numbers_counter:
    class: Mannion007\LongRunningProcess\Domain\AllPhoneNumbersCounter

  matched_phone_number_counter:
    class: Mannion007\LongRunningProcess\Domain\MatchedPhoneNumberCounter

  phone_number_executive:
    class: Mannion007\LongRunningProcess\Domain\PhoneNumberExecutive
    arguments:
      - '@phone_number_provider'
      - '@search_result_logger'
      - '@symfony_dispatcher_event_publisher'

  find_phone_numbers_listener:
    class: Mannion007\LongRunningProcess\EventListener\FindPhoneNumbersListener
    arguments:
      - '@phone_number_finder'
      - '@symfony_dispatcher_event_publisher'

  count_all_phone_numbers_listener:
    class: Mannion007\LongRunningProcess\EventListener\CountAllPhoneNumbersListener
    arguments:
      - '@all_phone_numbers_counter'
      - '@symfony_dispatcher_event_publisher'

  count_matched_phone_numbers_listener:
    class: Mannion007\LongRunningProcess\EventListener\CountMatchedPhoneNumbersListener
    arguments:
      - '@matched_phone_number_counter'
      - '@symfony_dispatcher_event_publisher'

  complete_matched_phone_numbers_counted_listener:
    class: Mannion007\LongRunningProcess\EventListener\CompleteMatchedPhoneNumbersCountListener
    arguments:
      - '@phone_number_executive'

  complete_all_phone_numbers_counted_listener:
    class: Mannion007\LongRunningProcess\EventListener\CompleteAllPhoneNumbersCountListener
    arguments:
      - '@phone_number_executive'